### ISSUE TITLE
Support for more storage backend providers

### ISSUE THREAD

**Issue by aldy505** [getsentry/vroom#188]
Current implementation of vroom is to only support [GCS](https://cloud.google.com/storage/) as the storage backend. It is used multiple times (as `env.profilesBucket`):

* https://github.com/getsentry/vroom/blob/971ab433d1bf57613527add8416179f99a86004c/cmd/vroom/flamegraph.go#L66
* https://github.com/getsentry/vroom/blob/971ab433d1bf57613527add8416179f99a86004c/cmd/vroom/profile.go#L65
* https://github.com/getsentry/vroom/blob/971ab433d1bf57613527add8416179f99a86004c/cmd/vroom/profile.go#L220
* https://github.com/getsentry/vroom/blob/971ab433d1bf57613527add8416179f99a86004c/cmd/vroom/profile.go#L293

It's not suitable for self-hosted version in which will be in GA by late April/beginning of May (per @phacops said). This issue tackles the support for more storage backend providers other than GCS specifically for self-hosted support. 

Some ideas:
- AWS S3 (people should put their bucket configuration on the .env file) - Self-hosted version can use [Minio](https://github.com/minio/minio), but I'd argue that it would take more load to the service stack.
- [BoltDB](https://github.com/boltdb/bolt)/[BadgerDB](https://github.com/dgraph-io/badger) (persisted to disk, can be mounted as normal Docker volume). GCS is basically a KV database, so this would do fine. -- Personally, I support this option more than the first one.

Although I support having BoltDB (or BadgerDB) as the primary storage backend for self-hosted, I think most people who deployed their Sentry instance on cloud services such as AWS, GCP, and Azure should have an option to get a nice and cheap storage bucket. It's nice if we give people more options for that one.

The downside of the above statement is that we have to maintain each implementation. Although during the development process, it's easy because for AWS S3 we have [Minio](https://github.com/minio/minio), Azure we have [Azurite](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio) and we have [some fake-gcs-server Docker image](https://hub.docker.com/r/fsouza/fake-gcs-server) that is used on the [deployment docker-compose file](https://github.com/getsentry/vroom/blob/971ab433d1bf57613527add8416179f99a86004c/deployments/docker-compose.yml#L3-L9). We will still need to assess and maintain the real/live version of storage backend implementations. 

Any feedbacks on this thoughts is appreciated. 

Reference: https://discord.com/channels/621778831602221064/796028405833007104/1081879715645763624

**Comment by aldy505** [comment]
Putting this here before I forget things. 

Change *storage.BucketHandler to be an interface. Then we should implement with some storage backend providers. https://github.com/getsentry/vroom/blob/main/internal/storageutil/gcs.go

**Comment by aldy505** [comment]
Hi @cleptric and @phacops, I've updated the issue with much more detail, as I have some free time now. Any thoughts/feedbacks are appreciated.

**Comment by phacops** [comment]
Thanks @aldy505 for describing the issue.

Perhaps it'd be wise to take a look at prior work like https://github.com/google/go-cloud. We'd open a bucket when creating the environment and pass that down to `UnmarshalCompressed` and `CompressedWrite` to read/write from the blob store (instead of just passing a bucket name) and the cloud aspect of things would be handled by the library. We wouldn't have to define our own interface like that.

For testing, we could keep the `fake-gcs-server` and use the library to connect to it like it's GCS perhaps.

**Comment by aldy505** [comment]
Okay, I'll work on this one.
