### ISSUE TITLE
Support for Clickhouse as an alternative to BigQuery

### ISSUE THREAD

**Issue by aldy505** [getsentry/vroom#189]
I don't know if this issue will be compulsory for self-hosted version of profiling feature and I am well aware that having BigQuery is optional, but here we go:

https://github.com/getsentry/vroom/blob/971ab433d1bf57613527add8416179f99a86004c/cmd/vroom/main.go#L61-L65

vroom uses BigQuery as the storage for incoming occurrence. Although it is only used once here:

https://github.com/getsentry/vroom/blob/971ab433d1bf57613527add8416179f99a86004c/cmd/vroom/profile.go#L88-L98

I think it's nice if we can provide Clickhouse as an alternative for BigQuery, since it's already defined as one of Sentry's self-hosted service:

https://github.com/getsentry/self-hosted/blob/06662c6cdc8573f81b6a128c7bdb815efd5040ed/docker-compose.yml#L196-L213

**Comment by phacops** [comment]
This is likely going to be removed before GA or a self-hosted release as it was meant to keep stats for internal use. There will be a customer feature using that data, so it's not like customers will miss something, we just added this so we didn't have to wait for the UI of the feature to be released to have access to stats.

I'll follow-up here when we have a plan for all this.

**Comment by aldy505** [comment]
Per https://github.com/getsentry/vroom/commit/e639ae29ea32754ea93d177b2b6f3f1b698f7cb6 should this be closed? @phacops

**Comment by phacops** [comment]
Yes, this should be closed. Thanks @aldy505.
